move new cacerts.pem file to the archive directory

diff --git a/getMozillaCA b/getMozillaCA
--- a/getMozillaCA
+++ b/getMozillaCA
@@ -20,7 +20,7 @@
 #
 SCRIPT_NAME=`basename $0`
 SCRIPT_DIR=`dirname $0`
-VERSION="$SCRIPT_NAME  1  (18-JUN-2020)"
+VERSION="$SCRIPT_NAME  2  (26-JUN-2020)"
 #
 print_usage() {
     cat - <<EOT
@@ -55,7 +55,6 @@ unset cwd
 ###############################################################################
 #
 cafile="cacert.pem"
-#cafile="cacert-2020-01-01.pem"
 #
 while :
 do
@@ -151,6 +150,27 @@ rm ${SCRIPT_DIR}/moz_cacerts_last_modified.bak || exit 1
 #
 echo "${SCRIPT_NAME}: last modification:"
 cat ${SCRIPT_DIR}/moz_cacerts_last_modified | sed -e 's/last-modified: //'
+#
+###############################################################################
+#
+newName=$(date --date="$(cat ${SCRIPT_DIR}/moz_cacerts_last_modified)" +"cacerts-%Y-%m-%d.pem")
+#
+if [ "${newName}" = "" ]
+then
+    echo "${SCRIPT_NAME}: can't create new file name"
+    exit 1
+fi
+#
+if [ ! -r archive/${newName} ]
+then
+    echo "${SCRIPT_NAME}: add new file to archive"
+    mv cacert.pem archive/${newName} || exit 1
+else
+    echo "${SCRIPT_NAME}: file ${newName} already in archive"
+fi
+#
+cd ${SCRIPT_DIR} || exit 1
+git status
 #
 ###############################################################################
 #
